name: Go

on:
  pull_request:
    branches: [ main ]
    # paths:
    #   - '!ui/'
    #   - '!.vscode/'
    #   - '!.gitignore'
    #   - '!Makefile'
    
  release:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get release version
      id: release_version
      run: |
        version="${github_ref//refs\/tags\//}"
        echo "${version}"
        echo "::set-output name=version::${version}"
        echo "::set-output name=tag::${version}"
      env:
        github_ref: ${{ github.ref }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Set up Node.js ⚙️
      uses: actions/setup-node@v3.3.0
      with:
        node-version: '14.x'

    - name: Install Node.js dependencies
      working-directory: ui/
      run: |
        npm install --global yarn 
        npm install
        yarn export
#     - name: Build
#       working-directory: ./
#       run: go build -v ./...

#     - name: Test
#       working-directory: ./
#       run: go test -v ./...
