name: Set test status

on:
  workflow_dispatch:
  

jobs:

  trigger_build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/github-script@v5
        name: Trigger build
        with:
          script: |
            params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              workflow_id: 'dispatchci.yml'
            }
            console.log(params)
            result = await github.rest.actions.createWorkflowDispatch(params)
            console.log(result)
