on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  workflow_dispatch:
    
jobs:
  hola_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: removelabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'review-app'
          type: remove
      - uses: actions/checkout@v2
      -  uses: ./.github/actions
         with:
            who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
