name: WorkflowB
on: [push]
jobs:
  foo:
    name: "Foo"
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 3m
  required-for-merge:
    name: "test"
    runs-on: ubuntu-latest
    needs: [ foo ]
    steps:
      - name: Fail
        run: false
